/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BuildingProjectUpdateManyWithoutAdressesInput } from "./BuildingProjectUpdateManyWithoutAdressesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ConstructionUpdateManyWithoutAdressesInput } from "./ConstructionUpdateManyWithoutAdressesInput";

@InputType()
class AdressUpdateInput {
  @ApiProperty({
    required: false,
    type: () => BuildingProjectUpdateManyWithoutAdressesInput,
  })
  @ValidateNested()
  @Type(() => BuildingProjectUpdateManyWithoutAdressesInput)
  @IsOptional()
  @Field(() => BuildingProjectUpdateManyWithoutAdressesInput, {
    nullable: true,
  })
  buildingProjects?: BuildingProjectUpdateManyWithoutAdressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: () => ConstructionUpdateManyWithoutAdressesInput,
  })
  @ValidateNested()
  @Type(() => ConstructionUpdateManyWithoutAdressesInput)
  @IsOptional()
  @Field(() => ConstructionUpdateManyWithoutAdressesInput, {
    nullable: true,
  })
  constructions?: ConstructionUpdateManyWithoutAdressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  state?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  streetname?: string | null;
}

export { AdressUpdateInput as AdressUpdateInput };
