/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BuildingProjectCreateNestedManyWithoutAdressesInput } from "./BuildingProjectCreateNestedManyWithoutAdressesInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { ConstructionCreateNestedManyWithoutAdressesInput } from "./ConstructionCreateNestedManyWithoutAdressesInput";

@InputType()
class AdressCreateInput {
  @ApiProperty({
    required: false,
    type: () => BuildingProjectCreateNestedManyWithoutAdressesInput,
  })
  @ValidateNested()
  @Type(() => BuildingProjectCreateNestedManyWithoutAdressesInput)
  @IsOptional()
  @Field(() => BuildingProjectCreateNestedManyWithoutAdressesInput, {
    nullable: true,
  })
  buildingProjects?: BuildingProjectCreateNestedManyWithoutAdressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: () => ConstructionCreateNestedManyWithoutAdressesInput,
  })
  @ValidateNested()
  @Type(() => ConstructionCreateNestedManyWithoutAdressesInput)
  @IsOptional()
  @Field(() => ConstructionCreateNestedManyWithoutAdressesInput, {
    nullable: true,
  })
  constructions?: ConstructionCreateNestedManyWithoutAdressesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  postcode?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  state?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  streetname?: string | null;
}

export { AdressCreateInput as AdressCreateInput };
