/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BuildingProjectListRelationFilter } from "../../buildingProject/base/BuildingProjectListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ConstructionListRelationFilter } from "../../construction/base/ConstructionListRelationFilter";
import { IntFilter } from "../../util/IntFilter";

@InputType()
class AdressWhereInput {
  @ApiProperty({
    required: false,
    type: () => BuildingProjectListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BuildingProjectListRelationFilter)
  @IsOptional()
  @Field(() => BuildingProjectListRelationFilter, {
    nullable: true,
  })
  buildingProjects?: BuildingProjectListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  city?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ConstructionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ConstructionListRelationFilter)
  @IsOptional()
  @Field(() => ConstructionListRelationFilter, {
    nullable: true,
  })
  constructions?: ConstructionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  country?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  postcode?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  state?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  streetname?: StringNullableFilter;
}

export { AdressWhereInput as AdressWhereInput };
