/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ConstructionService } from "../construction.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ConstructionCreateInput } from "./ConstructionCreateInput";
import { Construction } from "./Construction";
import { ConstructionFindManyArgs } from "./ConstructionFindManyArgs";
import { ConstructionWhereUniqueInput } from "./ConstructionWhereUniqueInput";
import { ConstructionUpdateInput } from "./ConstructionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ConstructionControllerBase {
  constructor(
    protected readonly service: ConstructionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Construction })
  @nestAccessControl.UseRoles({
    resource: "Construction",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createConstruction(
    @common.Body() data: ConstructionCreateInput
  ): Promise<Construction> {
    return await this.service.createConstruction({
      data: {
        ...data,

        adress: data.adress
          ? {
              connect: data.adress,
            }
          : undefined,

        buildingProjects: data.buildingProjects
          ? {
              connect: data.buildingProjects,
            }
          : undefined,
      },
      select: {
        adress: {
          select: {
            id: true,
          },
        },

        buildingProjects: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Construction] })
  @ApiNestedQuery(ConstructionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Construction",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async constructions(@common.Req() request: Request): Promise<Construction[]> {
    const args = plainToClass(ConstructionFindManyArgs, request.query);
    return this.service.constructions({
      ...args,
      select: {
        adress: {
          select: {
            id: true,
          },
        },

        buildingProjects: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Construction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Construction",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async construction(
    @common.Param() params: ConstructionWhereUniqueInput
  ): Promise<Construction | null> {
    const result = await this.service.construction({
      where: params,
      select: {
        adress: {
          select: {
            id: true,
          },
        },

        buildingProjects: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Construction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Construction",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateConstruction(
    @common.Param() params: ConstructionWhereUniqueInput,
    @common.Body() data: ConstructionUpdateInput
  ): Promise<Construction | null> {
    try {
      return await this.service.updateConstruction({
        where: params,
        data: {
          ...data,

          adress: data.adress
            ? {
                connect: data.adress,
              }
            : undefined,

          buildingProjects: data.buildingProjects
            ? {
                connect: data.buildingProjects,
              }
            : undefined,
        },
        select: {
          adress: {
            select: {
              id: true,
            },
          },

          buildingProjects: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Construction })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Construction",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteConstruction(
    @common.Param() params: ConstructionWhereUniqueInput
  ): Promise<Construction | null> {
    try {
      return await this.service.deleteConstruction({
        where: params,
        select: {
          adress: {
            select: {
              id: true,
            },
          },

          buildingProjects: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
